### ISSUE TITLE
Dead code is not removed from switch statements

### ISSUE THREAD

**Issue by vincent-dm** [google/closure-compiler#1722]
I am trying to compile a separate version of my web app for each language.
Therefore, I want to include only the translations for that language, using the goog.LOCALE parameter I set during compilation.

However, this leads to this kind of output under advanced mode (example with `goog.LOCALE = "nl"`):
```js
var bs = function(){
  switch("nl") { 
    case "nl": return {"al": "mijn", "Nederlandstalige": "vertalingen"};
    case "fr": return {"tous": "mes", "traductions": "françaises"};
    default: return {"all": "my", "english": "translations"}
  }
}();
```
_(I added the whitespace for readability, the object with the translations is obviously also different in reality)_

The first case of this switch statement will always be true, so I don't understand why it is not removed by the Closure Compiler.

Am I doing something wrong or are these optimization not yet supported?

**Comment by Dominator008** [comment]
Which version of the Compiler are you using?

I think this has been fixed by https://github.com/google/closure-compiler/commit/8a468ed4abb4ececc5f24928aac2f8c354fea54e, but it's not released yet.

**Comment by vincent-dm** [comment]
Seems I was using an older version, I was able to compile i correctly now. Sorry!

**Comment by Dominator008** [comment]
It's interesting that
```js
var bs = function(){
  switch("nl") { 
    case "nl": return {"al": "mijn", "Nederlandstalige": "vertalingen"};
    case "fr": return {"tous": "mes", "traductions": "françaises"};
    default: return {"all": "my", "english": "translations"}
  }
}();
window.bs = bs;
```
doesn't seem to get optimized under ADVANCED because of https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/PeepholeRemoveDeadCode.java#L307

I think we can do better here.

**Comment by vincent-dm** [comment]
Yeah, and it seems that I closed the issue prematurely, as my effort to replicate the problem was broken, and it turns out it still exists. [I've made a gist](https://gist.github.com/vincent-dm/30701e1dbd5d13beb30b8e5e856e6fda) (source is Clojurescript).

The gist example uses the `(condp ...)` form in Clojurescript, which gives a different output than the one I pasted in this issue. However, it has the same problem of including both branches in the compiled output.

The comment at the bottom of my gist shows what happens when I use a case statement in clojurescript, which leads to the switch output form this issue.

**Comment by concavelenz** [comment]
@Dominator008 If you remove that line is there a unit tests that covers it?  Generally, I think it would be fine if the default is the last case.

**Comment by Dominator008** [comment]
@concavelenz Yes there is a test case where the default is not the last case.

**Comment by Dominator008** [comment]
Related: https://github.com/google/closure-compiler/issues/313
