### ISSUE TITLE
Can't complie ES6 Modules.

### ISSUE THREAD

**Issue by dev-mraj** [google/closure-compiler#2139]
Command Line:
```
java -jar compiler.jar --js_output_file ./../app.cls.js --js **.js  --js_module_root './' --process_common_js_modules --transform_amd_modules --language_
in ECMASCRIPT6
```

`./app.js`

```
import TestClass from './components/TestClass';
export default class Application {
    /**
     * dfdf
     * @var
     */
    constructor() {
        new TestClass();
    }
    /**
     * dfdf
     * @var
     */
    test() {
        alert('dfdf');
    }
}
```

`'./components/TestClass.js'`

```
export default class TestClass  {
    /**
     * dfdf
     * @var
     */
    constructor() {
        alert('test');
    }
    /**
     * dfdf
     * @var
     */
    test() {
    }
}
```

```
WARNING - Failed to load module "components/TestClass.js"

app.js:2: ERROR - required "module$components$TestClass" namespace never provided
import TestClass from 'components/TestClass';
^

1 error(s), 1 warning(s)
```

**Comment by dev-mraj** [comment]
fixed is using **/*.js

**Comment by ChadKillingsworth** [comment]
I plan on adding a better error message for this case. It comes up often.

**Comment by dev-mraj** [comment]
That will be great..
i was struggling whole day for this small error

**Comment by jart** [comment]
If you remove the `--js_module_root ./` flag then what you did should work. That flag is meant to strip prefixes off the filename paths passed to the compiler via flags. I don't think it actually takes the file system into consideration. So because the `./` was being stripped, it started treating your imports as relative to the current directory, rather than being relative to the source file basename.

**Comment by sveryovka** [comment]
Hi. I've just tried example from this post using closure-compiler-v20180204.jar and I still get 
--
app.js:1: ERROR - Failed to load module "./components/TestClass"
import TestClass from './components/TestClass';
^

1 error(s), 0 warning(s)
--
I have tried removing "--js_module_root ./" and changing "--js **.js" to "--js */.js" but with no luck. 

Im I doing something wrong?

**Comment by jart** [comment]
Note for anyone reading in the future, TensorBoard learned the hard way that ES6 modules are grimly fiendish. https://github.com/tensorflow/tensorboard/pull/747
